apiVersion: apps/v1
kind: Deployment
metadata:
  name:  api-conversao
  namespace: default
  labels:
    app:  api-conversao
spec:
  selector:
    matchLabels:
      app: api-conversao
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  api-conversao
    spec:
      containers:
      - name:  api-conversao
        image:  igorferreira/api-conversao:latest
        ports:
        - containerPort:  8080
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
      restartPolicy: Always