apiVersion: v1
kind: Service
metadata:
  name:  api-conversao-service
spec:
  selector:
    app: api-conversao
  ports:
  - name:  http-svc
    port:  80
    protocol: TCP
    targetPort: 8080
  type:  LoadBalancer # LoadBalancer | ClusterIP | NodePort